name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag xanmod_builder:latest

      - name: Run the Docker image
        run: |
          WORKFLOW_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          docker run -i -e GITHUB_KEY=${{ secrets.GH_TOKEN }} \
            -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
            -e WORKFLOW_URL=${WORKFLOW_URL} xanmod_builder:latest
